### ISSUE TITLE
Adding Gulp

### ISSUE THREAD

**Issue by roboflank** [jheneknights/knightstart#1]
Can we include gulp, as an optional dev dependency? Then somehow one can choose to use either Grunt or Gulp as the build system? Optionally. I have nothing against Grunt though.

**Comment by kn9ts** [comment]
Yes I agree with you there. Could you fork and create the gulp config that does what gruntjs does...community contribution :dancers:

**Comment by roboflank** [comment]
Definitely :-)  Working on that.

**Comment by kn9ts** [comment]
Cheers man, appreciate it.

**Comment by roboflank** [comment]
I have created a pull request but more changes are on the way. [https://github.com/kn9ts/start/pull/2].

We will use this thread to keep track of the changes and any updates. :+1:

**Comment by kn9ts** [comment]
Merged, awaiting next updates

**Comment by roboflank** [comment]
@kn9ts is there a way the folder structure can be optimized in a way that all styles files are stored in one folder, that is in /styles folder then the types have their folder inside the /styles folder.
That is the less, css, e.t.c be under /styles folder.Is it convenient or it will alter the way grunt works?

**Comment by kn9ts** [comment]
Please find the Gulp alternative here -- [https://github.com/kn9ts/start-to-gulp](https://github.com/kn9ts/start-to-gulp)
